apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    # Configure your email here...
    # ---
    # email: your-email@address

    # Configure your server here...
    # ---
    # Letsencrypt Production
    # server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    # Configure DNS or HTTP Challenge here...
    # ---
    # DNS Challenge:
    # - dns01:
        # Configure your DNS Provider here...
        # ---
        # cloudflare:
        #   email: your-email@address
        # API Key:
        #   apiKeySecretRef:
        #     name: cloudflare-api-key-secret
        #     key: api-key
        # - or -
        # API Token:
        #   apiTokenSecretRef:
        #     name: cloudflare-api-token-secret
        #     key: api-token        
      # (Optional) Add DNS selectors
      # ---
      # selector:
      #   dnsZones:
      #   - 'your-domain'

    # HTTP Challenge:
    # - http01:
    #    ingress:
    #      class: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: app-test-1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-1-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "nginx.cloud.carabillo.eu"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-1-svc 
            port:
              number: 80
  tls:
  - hosts:
    - nginx.cloud.carabillo.eu
    secretName: app-test-1-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-test-1-cert
  namespace: app-test-1
spec:
  secretName: app-test-1-tls-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - nginx.cloud.carabillo.eu